import alimentacion from '../assets/uicons-categorias/alimentacion.svg'
import { AiOutlineHome } from "react-icons/ai";


const iconMapper = {
    Impuestos: 'account_balance',
    IVA: 'account_balance',
    ReteFuente: 'account_balance',
    ReteICA: 'account_balance',
    Cuotas_de_Manejo: 'account_balance',
    CuatroxMil: 'account_balance',
    Transacciones: 'account_balance',
    Otros_Impuestos: 'account_balance',
    Vivienda: 'Home',
    Hogar: 'chair',
    Arriendo:'apartment',
    Fechas_Especiales: 'celebration',
    Transporte: 'directions_car',
    Poliza: 'encrypted',
    Soat: 'add_moderator',
    Combustible: 'local_gas_station',
    Parqueadero: 'local_parking',
    Mantenimiento_Carro: 'local_car_wash',
    Taxi: 'local_car_wash',
    Bus: 'directions_bus',
    Inversion: 'finance_chip',
    Credito_Carro: 'directions_car',
    Finca_Raiz:'home_work',
    Deuda: 'payments',
    Nomina: 'group',
    Proveedores: 'engineering',
    Entretenimiento: 'attractions',
    Salidas: 'attractions',
    Licor: 'sports_bar',
    Alimentacion: 'restaurant_menu',
    Servicios: 'shower',
    Internet: 'language',
    Agua: 'water_drop',
    Electricidad: 'bolt',
    Celular: 'phone_iphone',
    Gas: 'valve',
    Salud: 'ecg_heart',
    EPS: 'home_health',
    Peluqueria: 'content_cut',
    Medicina: 'medical_services',
    Vacaciones: 'flight',
    Suscripciones: 'price_check',
    Nube: 'cloud',
    Adobe: 'design_services',
    Musica: 'headphones',
    Software: 'terminal',
    Mercado: 'shopping_cart',
    Imprevistos: 'help',
    Publicidad: 'cast_connected',
    Reuniones_Laborales: 'business_center',
    Ropa: 'checkroom',
    Educación: 'school',
  };
  
  export default iconMapper;